apiVersion: v1
kind: Service
metadata:
  name: wolfcode-external-domain # service的名称
  namespace: namespace-0327
  labels:
    app: wolfcode-external-domain # service本身的标签
spec:
  type: ExternalName # 有四种类型， NodePort， ClusterIP， LoadBalancer， ExternalName
  externalName: www.wolfcode.com

