grpc:
  server:
    port: 9092 #默认9090

server:
  port: 8771
spring:
  application:
    name: grpc-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: grpc-demo
