---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-svc
  namespace: namespace-0327
  labels:
    app: nginx-web-svc
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx-web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-web
  namespace: namespace-0327
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: local-path-volume2
              mountPath: /usr/share/nginx/html
  # 使用 volumeClaimTemplates 替代手动创建 PVC 和 spec.volumes
  volumeClaimTemplates:
    - metadata:
        name: local-path-volume2 # 对应上面 volumeMounts 中的 name
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path # 沿用你原本的 StorageClass
        resources:
          requests:
            storage: 1Gi