apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-pv-test-pvc
  namespace: namespace-0327
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: managed-nfs-storage
