---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sc
  namespace: namespace-0327
  labels:
    app: nginx-sc
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: web
  selector:
    app: nginx-sc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sc
  namespace: namespace-0327
spec:
  replicas: 1
  serviceName: "nginx-sc"
  selector:
    matchLabels:
      app: nginx-sc
  template:
    metadata:
      labels:
        app: nginx-sc
    spec:
      nodeName: worker001
      containers:
        - name: nginx-sc
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/local/nginx/html
              name: nginx-sc-test-pvc
  volumeClaimTemplates:
    - metadata:
        name: nginx-sc-test-pvc
      spec:
        storageClassName: managed-nfs-storage
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 500Mi
