apiVersion: v1
kind: ConfigMap
metadata:
  name: mvn-settings
  namespace: devops-test
  labels:
    app: jenkins-server
data:
  settings.xml: |-
    <?xml version="1.0"?>
    <settings>
        <localRepository>/var/jenkins_home/repository</localRepository>
        <pluginGroups>
            <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
        </pluginGroups>
        
        <servers>
            <server>
                <id>maven-releases</id>
                <username>developteam</username>
                <password>developteam</password>
            </server>
            <server>
                <id>maven-snapshots</id>
                <username>developteam</username>
                <password>developteam</password>
            </server>
            <server>
                <id>maven-central</id>
                <username>developteam</username>
                <password>developteam</password>
            </server>
            <server>
                <id>maven-public</id>
                <username>developteam
                </username>
                <password>developteam</password>
            </server>
            <server>
                <id>central</id>
                <username>developteam</username>
                <password>developteam</password>
            </server>
            <server>
                <id>releases
                </id>
                <username>developteam</username>
                <password>developteam
                </password>
            </server>
            <server>
                <id>snapshots</id>
                <username>developteam</username>
                <password>developteam</password>
            </server>
            <server>
                <id>public</id>
                <username>developteam</username>
                <password>developteam</password>
            </server>
            <server>
                <id>nexus</id>
                <username>developteam</username>
                <password>developteam</password>
            </server>
        </servers>
        
        <!-- ======================================================================== -->
        <!--  mirror settings                                                         -->
        <!-- ======================================================================== -->
        <mirrors>
            <mirror>
                <id>leyao</id>
                <mirrorOf>*</mirrorOf>
                <name>leyao Repository Mirror.</name>
                <url>https://nexus.streamcomputing.com/repository/maven-central/</url>
            </mirror>
            <mirror>
                <id>maven-central</id>
                <mirrorOf>maven-central</mirrorOf>
                <name>leyao Repository Mirror.</name>
                <url>https://nexus.streamcomputing.com/repository/maven-central/</url>
            </mirror>
            <mirror>
                <id>maven-public</id>
                <mirrorOf>maven-public</mirrorOf>
                <name>leyao Repository Mirror.</name>
                <url>https://nexus.streamcomputing.com/repository/maven-public/</url>
            </mirror>
            <mirror>
                <id>maven-releases</id>
                <mirrorOf>maven-releases</mirrorOf>
                <name>leyao Repository Mirror.
                </name>
                <url>https://nexus.streamcomputing.com/repository/maven-releases/
                </url>
            </mirror>
            <mirror>
                <id>maven-snapshots</id>
                <mirrorOf>maven-snapshots</mirrorOf>
                <name>leyao Repository Mirror.</name>
                <url>https://nexus.streamcomputing.com/repository/maven-snapshots/</url>
            </mirror>
        </mirrors>
        
        <profiles>
            <profile>
                <id>nexus</id>
                <properties>
                    <sonar.host.url>http://sonarqube:9000</sonar.host.url>
                </properties>
                <repositories>
                    <repository>
                        <id>maven-central</id>
                        <url>https://nexus.streamcomputing.com/repository/maven-central/</url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                    </repository>
                    <repository>
                        <id>maven-public</id>
                        <url>https://nexus.streamcomputing.com/repository/maven-public/</url>
                        <releases>
                            <enabled>true
                            </enabled>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                    </repository>
                    <repository>
                        <id>maven-releases
                        </id>
                        <url>https://nexus.streamcomputing.com/repository/maven-releases/</url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                    </repository>
                    <repository>
                        <id>maven-snapshots
                        </id>
                        <url>https://nexus.streamcomputing.com/repository/maven-snapshots/
                        </url>
                        <releases>
                            <enabled>false</enabled>
                        </releases>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                    </repository>
                    <repository>
                        <id>ysbang</id>
                        <url>https://nexus.streamcomputing.com/repository/maven-ysbang/</url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                    </repository>
                </repositories>
                <pluginRepositories>
                    <pluginRepository>
                        <id>maven-central
                        </id>
                        <url>https://nexus.streamcomputing.com/repository/maven-central/
                        </url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                    </pluginRepository>
                    <pluginRepository>
                        <id>maven-public</id>
                        <url>https://nexus.streamcomputing.com/repository/maven-public/</url>
                        <releases>
                            <enabled>true
                            </enabled>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                    </pluginRepository>
                    <pluginRepository>
                        <id>maven-releases</id>
                        <url>https://nexus.streamcomputing.com/repository/maven-releases/</url>
                        <releases>
                            <enabled>true</enabled>
                        </releases>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                    </pluginRepository>
                    <pluginRepository>
                        <id>maven-snapshots</id>
                        <url>https://nexus.streamcomputing.com/repository/maven-snapshots/</url>
                        <releases>
                            <enabled>false</enabled>
                        </releases>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                    </pluginRepository>
                </pluginRepositories>
            </profile>
        </profiles>
        
        <activeProfiles>
            <activeProfile>nexus</activeProfile>
        </activeProfiles>
    </settings>