apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: namespace-0327
spec:
  replicas: 1 # 副本数量
  revisionHistoryLimit: 10 # 进行滚动更新后，保留的历史版本数量
  selector: # 用于找到匹配的replicaset
    matchLabels: # 按照标签匹配
      app: nginx-deploy # 匹配到的标签
  strategy: # 更新策略
    rollingUpdate: # 滚动更新配置
      maxSurge: 25% # 进行滚动更新时，同时启动最多25%的新实例
      maxUnavailable: 25% # 进行滚动更新时，同时停止最多25%的旧实例
    type: RollingUpdate # 更新类型，采用滚动更新
  template: # pod模板
    metadata: # pod元信息
      labels: # pod的标签
        app: nginx-deploy
    spec: # pod的期望信息
      containers: # pod的容器
        - image: nginx:1.9.1 # pod的镜像
          imagePullPolicy: IfNotPresent # 拉取策略
          name: nginx # 容器的名称
          command: ['/bin/sh', '-c', 'nginx daemon off; sleep 3600']
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts: # 挂载数据卷
            - name: nginx-conf # 数据卷名称
              mountPath: '/etc/nginx' # 挂载的路径
      volumes: # 数据卷定义
        - name: nginx-conf # 数据卷名称
          configMap: # 数据卷的类型为configmap
            name: nginx-conf-cm # configmap的名称
            items: # 将configmap中哪些数据挂载进来
              - key: nginx.conf # 指定挂载哪一个key
                path: nginx.conf # 挂载后该key重命名为什么名字
      restartPolicy: Always # 重启策略
      terminationGracePeriodSeconds: 30 # 删除操作最多宽限多少时间
