server:
   port: 8763
spring:
   redis:
      host: 127.0.0.1
      port: 6379
   application:
      name: springboot-demo
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/province_city_county?useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      schema: classpath:sql/schema.sql
  

mybatis:
   mapperLocations: classpath:mapper/*.xml
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  