server:
   port: 8763
spring:
   jackson:
      deserialization:
        fail-on-unknown-properties: false # Jackson，在将 JSON 或其他格式的数据映射到 Java 对象时，如果发现对象中没有对应的属性，不要抛出异常，而是直接忽略它。
   data:
     redis:
        host: 127.0.0.1
        port: 6379
        password: password
        timeout: 10000
        database: 0
   application:
      name: springboot-demo
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/db_spring_demo?useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
   thymeleaf:
      mode: HTML
      cache: false # 此属性默认在开发环境中为 true。将其设置为 false 后，Thymeleaf 每次请求页面时都会重新加载和解析模板文件，从而让你的修改立即生效。3.最后在每次修改静态内容时按Ctrl+Shift+F9即可重新加载
      prefix: classpath:/templates/
      encoding: UTF-8
      suffix: .html
      check-template-location: true
      template-resolver-order: 1
   mail:
      host: smtp.qq.com
      username: 1962270215@qq.com
      password: npuiajnodauybjeh
      port: 465
      protocol: smtp
      default-encoding: UTF-8
      properties:
         mail:
            smtp:
               ssl:
                  enable: true
               socketFactory:
                  port: 465
                  class: javax.net.ssl.SSLSocketFactory
         debug: true


mybatis:
   mapperLocations: classpath:mapper/*.xml
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
   # token 名称（同时也是 cookie 名称）
   token-name: satoken
   # token 有效期（单位：秒） 默认30天，-1 代表永久有效
   timeout: 2592000
   # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
   active-timeout: -1
   # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
   is-concurrent: true
   # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
   is-share: false
   # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
   token-style: uuid
   # 是否输出操作日志
   is-log: true
   jwt-secret-key: password
custom:
   data:
      -
         name: springboot-name
         value: springboot-value
      -
         name: springboot-name2
         value: springboot-value2
      -
         name: springboot-name3
         value: springboot-value3
   name: springboot-demo
   value: 1.0.0

rocketmq:
  name-server: 172.16.31.99:9876
  producer:
     group: springboot-demo-producer
     # 发送消息超时时间，默认3000
     sendMessageTimeout: 10000
     # 发送消息失败重试次数，默认2
     retryTimesWhenSendFailed: 2
     # 异步消息重试此处，默认2
     retryTimesWhenSendAsyncFailed: 2
     # 消息最大长度，默认1024 * 1024 * 4(默认4M)
     maxMessageSize: 4096
     # 压缩消息阈值，默认4k(1024 * 4)
     compressMessageBodyThreshold: 4096
     # 是否在内部发送失败时重试另一个broker，默认false
     retryNextServer: false
  consumer:
     group: springboot-demo-consumer
     # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
     pull-batch-size: 10
