server:
   port: 8763
spring:
   data:
     redis:
        host: 127.0.0.1
        port: 6379
        password: password
        timeout: 10000
        database: 0
   application:
      name: springboot-demo
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/db_spring_demo?useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  

mybatis:
   mapperLocations: classpath:mapper/*.xml
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  