apiVersion: v1
data:
  cluster-mapping.json: {clusterMappingJson}
  config.json: {configJson}
kind: ConfigMap
metadata:
  labels:
    app: {app}
    managed-by: {managedBy}
  name: {configName}
  namespace: {namespace}
