apiVersion: v1
data:
  userID: {userId}
  userKey: {userKey}
kind: Secret
metadata:
  labels:
    app: {app}
    ceph-cluster-id: {cephClusterId}
    managed-by: {managerBy}
  name: {secretName}
  namespace: {namespace}
type: {type}
